
package mythapi.frontend;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * Interface Version 2.1 - 
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FrontendServices", targetNamespace = "http://mythtv.org", wsdlLocation = "file:/tmp/mythtv/wsdl")
public class FrontendServices
    extends Service
{

    private final static URL FRONTENDSERVICES_WSDL_LOCATION;
    private final static WebServiceException FRONTENDSERVICES_EXCEPTION;
    private final static QName FRONTENDSERVICES_QNAME = new QName("http://mythtv.org", "FrontendServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/tmp/mythtv/wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FRONTENDSERVICES_WSDL_LOCATION = url;
        FRONTENDSERVICES_EXCEPTION = e;
    }

    public FrontendServices() {
        super(__getWsdlLocation(), FRONTENDSERVICES_QNAME);
    }

    public FrontendServices(WebServiceFeature... features) {
        super(__getWsdlLocation(), FRONTENDSERVICES_QNAME, features);
    }

    public FrontendServices(URL wsdlLocation) {
        super(wsdlLocation, FRONTENDSERVICES_QNAME);
    }

    public FrontendServices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FRONTENDSERVICES_QNAME, features);
    }

    public FrontendServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FrontendServices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Frontend
     */
    @WebEndpoint(name = "BasicHttpBinding_Frontend")
    public Frontend getBasicHttpBindingFrontend() {
        return super.getPort(new QName("http://mythtv.org", "BasicHttpBinding_Frontend"), Frontend.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Frontend
     */
    @WebEndpoint(name = "BasicHttpBinding_Frontend")
    public Frontend getBasicHttpBindingFrontend(WebServiceFeature... features) {
        return super.getPort(new QName("http://mythtv.org", "BasicHttpBinding_Frontend"), Frontend.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FRONTENDSERVICES_EXCEPTION!= null) {
            throw FRONTENDSERVICES_EXCEPTION;
        }
        return FRONTENDSERVICES_WSDL_LOCATION;
    }

}
