
package mythapi.frontend;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Frontend", targetNamespace = "http://mythtv.org")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Frontend {


    /**
     * GET 
     * 
     * @param context
     * @return
     *     returns mythapi.frontend.FrontendActionList
     */
    @WebMethod(operationName = "GetActionList", action = "http://mythtv.org/Frontend/GetActionList")
    @WebResult(name = "GetActionListResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetActionList", targetNamespace = "http://mythtv.org", className = "mythapi.frontend.GetActionList")
    @ResponseWrapper(localName = "GetActionListResponse", targetNamespace = "http://mythtv.org", className = "mythapi.frontend.GetActionListResponse")
    public FrontendActionList getActionList(
        @WebParam(name = "Context", targetNamespace = "http://mythtv.org")
        String context);

    /**
     * GET 
     * 
     * @return
     *     returns mythapi.frontend.ArrayOfString
     */
    @WebMethod(operationName = "GetContextList", action = "http://mythtv.org/Frontend/GetContextList")
    @WebResult(name = "GetContextListResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetContextList", targetNamespace = "http://mythtv.org", className = "mythapi.frontend.GetContextList")
    @ResponseWrapper(localName = "GetContextListResponse", targetNamespace = "http://mythtv.org", className = "mythapi.frontend.GetContextListResponse")
    public ArrayOfString getContextList();

    /**
     * GET 
     * 
     * @return
     *     returns mythapi.frontend.FrontendStatus
     */
    @WebMethod(operationName = "GetStatus", action = "http://mythtv.org/Frontend/GetStatus")
    @WebResult(name = "GetStatusResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "GetStatus", targetNamespace = "http://mythtv.org", className = "mythapi.frontend.GetStatus")
    @ResponseWrapper(localName = "GetStatusResponse", targetNamespace = "http://mythtv.org", className = "mythapi.frontend.GetStatusResponse")
    public FrontendStatus getStatus();

    /**
     * POST 
     * 
     * @param chanId
     * @param startTime
     * @param recordedId
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "PlayRecording", action = "http://mythtv.org/Frontend/PlayRecording")
    @WebResult(name = "PlayRecordingResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "PlayRecording", targetNamespace = "http://mythtv.org", className = "mythapi.frontend.PlayRecording")
    @ResponseWrapper(localName = "PlayRecordingResponse", targetNamespace = "http://mythtv.org", className = "mythapi.frontend.PlayRecordingResponse")
    public Boolean playRecording(
        @WebParam(name = "RecordedId", targetNamespace = "http://mythtv.org")
        Integer recordedId,
        @WebParam(name = "ChanId", targetNamespace = "http://mythtv.org")
        Integer chanId,
        @WebParam(name = "StartTime", targetNamespace = "http://mythtv.org")
        XMLGregorianCalendar startTime);

    /**
     * POST 
     * 
     * @param useBookmark
     * @param id
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "PlayVideo", action = "http://mythtv.org/Frontend/PlayVideo")
    @WebResult(name = "PlayVideoResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "PlayVideo", targetNamespace = "http://mythtv.org", className = "mythapi.frontend.PlayVideo")
    @ResponseWrapper(localName = "PlayVideoResponse", targetNamespace = "http://mythtv.org", className = "mythapi.frontend.PlayVideoResponse")
    public Boolean playVideo(
        @WebParam(name = "Id", targetNamespace = "http://mythtv.org")
        String id,
        @WebParam(name = "UseBookmark", targetNamespace = "http://mythtv.org")
        Boolean useBookmark);

    /**
     * POST 
     * 
     * @param width
     * @param action
     * @param value
     * @param height
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "SendAction", action = "http://mythtv.org/Frontend/SendAction")
    @WebResult(name = "SendActionResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "SendAction", targetNamespace = "http://mythtv.org", className = "mythapi.frontend.SendAction")
    @ResponseWrapper(localName = "SendActionResponse", targetNamespace = "http://mythtv.org", className = "mythapi.frontend.SendActionResponse")
    public Boolean sendAction(
        @WebParam(name = "Action", targetNamespace = "http://mythtv.org")
        String action,
        @WebParam(name = "Value", targetNamespace = "http://mythtv.org")
        String value,
        @WebParam(name = "Width", targetNamespace = "http://mythtv.org")
        Long width,
        @WebParam(name = "Height", targetNamespace = "http://mythtv.org")
        Long height);

    /**
     * POST 
     * 
     * @param key
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "SendKey", action = "http://mythtv.org/Frontend/SendKey")
    @WebResult(name = "SendKeyResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "SendKey", targetNamespace = "http://mythtv.org", className = "mythapi.frontend.SendKey")
    @ResponseWrapper(localName = "SendKeyResponse", targetNamespace = "http://mythtv.org", className = "mythapi.frontend.SendKeyResponse")
    public Boolean sendKey(
        @WebParam(name = "Key", targetNamespace = "http://mythtv.org")
        String key);

    /**
     * POST 
     * 
     * @param message
     * @param timeout
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "SendMessage", action = "http://mythtv.org/Frontend/SendMessage")
    @WebResult(name = "SendMessageResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "SendMessage", targetNamespace = "http://mythtv.org", className = "mythapi.frontend.SendMessage")
    @ResponseWrapper(localName = "SendMessageResponse", targetNamespace = "http://mythtv.org", className = "mythapi.frontend.SendMessageResponse")
    public Boolean sendMessage(
        @WebParam(name = "Message", targetNamespace = "http://mythtv.org")
        String message,
        @WebParam(name = "Timeout", targetNamespace = "http://mythtv.org")
        Long timeout);

    /**
     * POST 
     * 
     * @param image
     * @param visibility
     * @param origin
     * @param description
     * @param error
     * @param type
     * @param message
     * @param priority
     * @param timeout
     * @param fullscreen
     * @param extra
     * @param progress
     * @param progressText
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "SendNotification", action = "http://mythtv.org/Frontend/SendNotification")
    @WebResult(name = "SendNotificationResult", targetNamespace = "http://mythtv.org")
    @RequestWrapper(localName = "SendNotification", targetNamespace = "http://mythtv.org", className = "mythapi.frontend.SendNotification")
    @ResponseWrapper(localName = "SendNotificationResponse", targetNamespace = "http://mythtv.org", className = "mythapi.frontend.SendNotificationResponse")
    public Boolean sendNotification(
        @WebParam(name = "Error", targetNamespace = "http://mythtv.org")
        Boolean error,
        @WebParam(name = "Type", targetNamespace = "http://mythtv.org")
        String type,
        @WebParam(name = "Message", targetNamespace = "http://mythtv.org")
        String message,
        @WebParam(name = "Origin", targetNamespace = "http://mythtv.org")
        String origin,
        @WebParam(name = "Description", targetNamespace = "http://mythtv.org")
        String description,
        @WebParam(name = "Image", targetNamespace = "http://mythtv.org")
        String image,
        @WebParam(name = "Extra", targetNamespace = "http://mythtv.org")
        String extra,
        @WebParam(name = "ProgressText", targetNamespace = "http://mythtv.org")
        String progressText,
        @WebParam(name = "Progress", targetNamespace = "http://mythtv.org")
        Float progress,
        @WebParam(name = "Timeout", targetNamespace = "http://mythtv.org")
        Integer timeout,
        @WebParam(name = "Fullscreen", targetNamespace = "http://mythtv.org")
        Boolean fullscreen,
        @WebParam(name = "Visibility", targetNamespace = "http://mythtv.org")
        Long visibility,
        @WebParam(name = "Priority", targetNamespace = "http://mythtv.org")
        Long priority);

}
